apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    helm.sh/chart: {{ include "redis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "redis.fullname" . }}
data:
  redis.conf: |-
{{- if .Values.configmap }}
    # User-supplied configuration:
{{ .Values.configmap | indent 4 }}
{{- end }}
  master.conf: |-
    dir {{ .Values.master.persistence.path }}
{{- if .Values.master.disableCommands }}
{{- range .Values.master.disableCommands }}
    rename-command {{ . }} ""
{{- end }}
{{- end }}
  replica.conf: |-
    dir /data
{{- $replicaDisabledCommands := default .Values.master.disableCommands .Values.slave.disableCommands }}
{{- if $replicaDisabledCommands }}
{{- range $replicaDisabledCommands }}
    rename-command {{ . }} ""
{{- end }}
{{- end }}
