{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ include "networkPolicy.apiVersion" . }}
metadata:
  name: "{{ include "redis.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    helm.sh/chart: {{ include "redis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "redis.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
    # Allow inbound connections
    - ports:
      - port: 6379
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{ include "redis.fullname" . }}-client: "true"
        {{- if .Values.metrics.enabled }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "redis.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: metrics
        {{- end }}
      {{- end }}
    {{- if .Values.metrics.enabled }}
    # Allow prometheus scrapes for metrics
    - ports:
      - port: 9121
    {{- end }}
{{- end }}
