apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-master
  labels:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    helm.sh/chart: {{ include "redis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: master
{{- with .Values.master.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.master.service.type }}
  {{ if eq .Values.master.service.type "LoadBalancer" -}} {{ if .Values.master.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.master.service.loadBalancerIP }}
  {{ end -}}
  {{- end -}}
  ports:
  - name: redis
    port: {{ .Values.master.service.port }}
    targetPort: redis
    {{- if .Values.master.service.nodePort }}
    nodePort: {{ .Values.master.service.nodePort }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: master
