{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-slave
  labels:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    helm.sh/chart: {{ include "redis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: slave
{{- if .Values.slave.service.annotations }}
  annotations:
{{ toYaml .Values.slave.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.slave.service.type }}
  {{ if eq .Values.slave.service.type "LoadBalancer" -}} {{ if .Values.slave.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.slave.service.loadBalancerIP }}
  {{ end -}}
  {{- end -}}
  ports:
  - name: redis
    port: 6379
    targetPort: redis
    {{- if .Values.slave.service.nodePort }}
    nodePort: {{ .Values.slave.service.nodePort }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: slave
{{- end}}
