{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postgresql.name" . }}
    helm.sh/chart: {{ include "postgresql.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.postgresqlPassword }}
  postgresql-password: {{ .Values.postgresqlPassword | b64enc | quote }}
  {{- else }}
  postgresql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.replication.enabled }}
  {{- if .Values.replication.password }}
  postgresql-replication-password: {{ .Values.replication.password | b64enc | quote }}
  {{- else }}
  postgresql-replication-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end -}}
